### ISSUE TITLE
Error when installing this package with pip

### ISSUE THREAD

**Issue by Tropaion** [Lewiscowles1986/py-call-graph#29]
Hello,
I can't get this package to work, I always get this error when installing:
```
python.exe -m pip install python-call-graph
Collecting python-call-graph
  Using cached python-call-graph-2.1.2.tar.gz (470 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Tropaion\AppData\Local\Temp\pip-install-5h3bhky2\python-call-graph_b62a800386f74f5d8b0f635478a3cd16\setup.py", line 10, in <module>
          import pycallgraph
      ModuleNotFoundError: No module named 'pycallgraph'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Levon-Wild** [comment]
I met this issue too. Is there any one knows how should I do to sovle it？

**Comment by Lewiscowles1986** [comment]
Do you have more information on python versions, OS's; if you've tried in a clean-room via `uv` or `poetry` or `venv`?
