### ISSUE TITLE
py-call-graph incompatible with projects using torch

### ISSUE THREAD

**Issue by gskt17** [Lewiscowles1986/py-call-graph#30]
I am trying to generate a call graph project which happens to use PyTorch. Running `pycallgraph graphviz -- ./main.py`, I get the following traceback:

```
Traceback (most recent call last):
  File "/var/www/PM-env/bin/pycallgraph", line 26, in <module>
    exec(__file_content)
  File "<string>", line 18, in <module>
  File [redacted for anonymization], in <module>
    import torch
  File "/var/www/PM-env/lib/python3.8/site-packages/torch/__init__.py", line 629, in <module>
    from .functional import *  # noqa: F403
  File "/var/www/PM-env/lib/python3.8/site-packages/torch/functional.py", line 6, in <module>
    import torch.nn.functional as F
  File "/var/www/PM-env/lib/python3.8/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/var/www/PM-env/lib/python3.8/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/var/www/PM-env/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 6, in <module>
    from .. import functional as F
  File "/var/www/PM-env/lib/python3.8/site-packages/torch/nn/functional.py", line 1278, in <module>
    _VF.threshold_,
  File "/var/www/PM-env/lib/python3.8/site-packages/torch/_VF.py", line 25, in __getattr__
    def __getattr__(self, attr):
  File "/var/www/PM-env/lib/python3.8/site-packages/pycallgraph/tracer.py", line 24, in tracer
    self.processor.process(frame, event, arg, self.memory())
  File "/var/www/PM-env/lib/python3.8/site-packages/pycallgraph/tracer.py", line 169, in process
    module_path = module.__file__
  File "/var/www/PM-env/lib/python3.8/site-packages/torch/_VF.py", line 26, in __getattr__
    return getattr(self.vf, attr)
AttributeError: 'torch._C._VariableFunctionsClass' object has no attribute '__file__'
```

If I am reading this correctly, it means that pycallgraph cannot make a call graph of any project using PyTorch.

**Comment by rtarquini** [comment]
I'm also seeing this error

**Comment by Lewiscowles1986** [comment]
Can anyone provide more information?

- OS
- OS Version
- Python version
- How you installed this package
- Package version installed

Can anyone help me make a minimal reproducible example?

**Comment by NicolasGrosjeanProbayes** [comment]
## Informations
 
- OS : Ubuntu 22.04.5 LTS
- Python : 3.10.12
- Installed with poetry
- Package version installed : python-call-graph 2.1.3 and torch 2.7.0

<details>
  <summary>Full dependencies (pip freeze)</summary>

ansible-base==2.10.8
apache-libcloud==3.2.0
apturl==0.5.2
argcomplete==1.8.1
Babel==2.8.0
beautifulsoup4==4.10.0
blinker==1.4
Brlapi==0.8.3
build==1.2.2
CacheControl==0.14.0
certifi==2020.6.20
chardet==4.0.0
charset-normalizer==3.3.2
cleo==2.1.0
click==8.0.3
colorama==0.4.4
command-not-found==0.3
crashtest==0.4.1
crudini==0.9.3
cryptography==3.4.8
css-parser==1.0.7
cssutils==1.0.2
cupshelpers==1.0
dbus-python==1.2.18
decorator==4.4.2
defer==1.0.6
distlib==0.3.8
distro==1.7.0
distro-info==1.1+ubuntu0.2
dnspython==2.1.0
dulwich==0.21.7
fastjsonschema==2.20.0
filelock==3.16.1
gajim==1.3.3
gssapi==1.6.12
html5lib==1.1
httplib2==0.20.2
idna==3.3
img2pdf==0.4.2
importlib_metadata==8.5.0
iniparse==0.4
installer==0.7.0
iotop==0.6
jaraco.classes==3.4.0
jeepney==0.7.1
Jinja2==3.0.3
jmespath==0.10.0
keyring==24.3.1
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lockfile==0.12.2
louis==3.20.0
lxml==4.8.0
macaroonbakery==1.3.1
Mako==1.1.3
Markdown==3.3.6
MarkupSafe==2.0.1
meld==3.20.4
more-itertools==8.10.0
msgpack==1.1.0
nbxmpp==2.0.4
netaddr==0.8.0
netifaces==0.11.0
ntlm-auth==1.4.0
numpy==1.21.5
oauthlib==3.2.0
olefile==0.46
packaging==24.1
pexpect==4.8.0
pikepdf==5.0.1+dfsg
Pillow==9.0.1
pkginfo==1.11.1
platformdirs==4.3.6
poetry==1.8.2
poetry-core==1.9.0
poetry-plugin-export==1.8.0
precis-i18n==1.0.2
protobuf==3.12.4
ptyprocess==0.7.0
pycairo==1.20.1
pycryptodomex==3.11.0
pycups==2.0.1
Pygments==2.11.2
PyGObject==3.42.1
PyJWT==2.3.0
pykerberos==1.1.14
pymacaroons==0.13.0
PyNaCl==1.5.0
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyproject_hooks==1.1.0
pyRFC3339==1.1
python-apt==2.4.0+ubuntu4
python-axolotl==0.2.3
python-axolotl-curve25519==0.4.1.post2
python-dateutil==2.8.1
python-debian==0.1.43+ubuntu1.1
python-distutils-extra==2.39
python-gnupg==0.4.8
python-magic==0.4.24
pytz==2022.1
pywinrm==0.3.0
pyxdg==0.27
PyYAML==5.4.1
qrcode==7.3.1
rapidfuzz==3.9.7
reportlab==3.6.8
requests==2.32.3
requests-kerberos==0.12.0
requests-ntlm==1.1.0
requests-toolbelt==1.0.0
s3cmd==2.2.0
SecretStorage==3.3.1
selinux==3.3
shellingham==1.5.4
simplejson==3.17.6
six==1.16.0
soupsieve==2.3.1
ssh-import-id==5.11
systemd-python==234
tomli==2.0.1
tomlkit==0.13.2
trove-classifiers==2024.9.12
ubuntu-drivers-common==0.0.0
ubuntu-pro-client==8001
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.5
virtualenv==20.26.5
wadllib==1.3.6
webencodings==0.5.1
xdg==5
xkit==0.0.0
xmltodict==0.12.0
zipp==3.20.2

</details>

## Reproducible example

Creating environment, add dependencies and activating it 

```bash
poetry init
poetry add torch
poetry add python-call-graph
poetry shell
```

Creating one line failing example

```bash
echo "import torch" > foo.py
```

Run on it

```bash
pycallgraph graphviz -- foo.py
```

**Comment by NicolasGrosjeanProbayes** [comment]
To go around the issue, I used the [API](https://github.com/Lewiscowles1986/py-call-graph?tab=readme-ov-file#a-simple-use-of-the-api-is) on the bloc of code to analyse (so after the import commands which cause issues with the command line).

**Comment by Lewiscowles1986** [comment]
If you have capacity to do the investigation and report back I'd be so appreciative. Otherwise I'm not sure I can merge in it's current state. Thank you in any case, because this does feel like quite the bug.

**Comment by Lewiscowles1986** [comment]
Can someone check if this is just the pickling / unpickling of the model leading to modules without names, which #36 has a reported fix for.

**Comment by Lewiscowles1986** [comment]
This should be resolved now, thanks to @NicolasGrosjeanProbayes work on #36 this merged in #38
