### ISSUE TITLE
CLI crash when trying to know the version

### ISSUE THREAD

**Issue by dgutson** [Lewiscowles1986/py-call-graph#33]
```
$ pycallgraph --version
usage: pycallgraph [options] OUTPUT_TYPE [output_options] -- SCRIPT.py [ARG ...]
pycallgraph: error: unrecognized arguments: --version
$ pycallgraph -v
Traceback (most recent call last):
  File "/home/xxx/.local/bin/pycallgraph", line 19, in <module>
    __config.strip_argv()
  File "/home/xxx/.local/share/pipx/venvs/python-call-graph/lib/python3.12/site-packages/pycallgraph/config.py", line 73, in strip_argv
    sys.argv = [self.command] + self.command_args
                ^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'command'
```

**Comment by Lewiscowles1986** [comment]
`pycallgraph: error: unrecognized arguments: --version` is the key piece of information

**Comment by Lewiscowles1986** [comment]
I think the -v might be verbose flag needing a command to be supplied as well

**Comment by Lewiscowles1986** [comment]
```
        self.parser.add_argument(
            '-v', '--verbose', action='store_true', default=self.verbose,
            help='Display informative messages while running')
```
is from [config.py](https://github.com/Lewiscowles1986/py-call-graph/blob/df8b7cee013c83784a48d9f3248a7451c712c08b/pycallgraph/config.py#L119-L121)

**Comment by Lewiscowles1986** [comment]
`pip freeze` should show you the version installed

**Comment by Lewiscowles1986** [comment]
`pycallgraph` module has a `__version__` attribute which you could check from code, or you could commit a version command.

**Comment by dgutson** [comment]
The time you took to write all these answers, and tagging this as "user education", was the time to add the `--version` option to the CLI. Maybe this attitude could be the reason the project has 114 stars. Instead of educating me, consider what is the cli option that the rest of the world uses.

**Comment by dgutson** [comment]
BTW:
" I’m currently learning about patience, persistence, advanced disaster recovery and compassionate, effective communication."

--> Try harder. I mean it. Or just quit.

**Comment by dgutson** [comment]
Thanks. Be in peace.
